# Generated by Django 6.1 on 2026-08-12 17:31

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('overview', models.TextField()),
                ('front_end_techs', models.CharField(max_length=160)),
                ('back_end_techs', models.CharField(max_length=160)),
                ('other_techs', models.CharField(max_length=160)),
                ('live_site', models.URLField()),
                ('challenges', models.ManyToManyField(blank=True, to='portfolio_app.challenge')),
                ('impacts', models.ManyToManyField(blank=True, to='portfolio_app.impact')),
                ('key_features', models.ManyToManyField(blank=True, to='portfolio_app.keyfeature')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=160)),
                ('long_description', models.TextField()),
                ('snapshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.detail')),
                ('features', models.ManyToManyField(blank=True, to='portfolio_app.feature')),
                ('industry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.industry')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio_app.technology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
