# Generated by Django 6.1 on 2026-08-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='overview',
        ),
    ]
