# Generated by Django 6.1 on 2026-08-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_challenge_feature_impact_industry_keyfeature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.AddField(
            model_name='detail',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolio_app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.industry'),
        ),
    ]
