# Generated by Django 6.1 on 2026-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='live_site',
        ),
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.URLField(default='https://tester.com'),
            preserve_default=False,
        ),
    ]
