# Generated by Django 6.1 on 2026-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_remove_detail_live_site_project_live_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
