# Generated by Django 6.1 on 2026-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='impacts',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio_app.impact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
