# Generated by Django 6.1 on 2026-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_detail_impacts_alter_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='impacts',
            field=models.ManyToManyField(blank=True, to='portfolio_app.impact'),
        ),
    ]
